name: 'Deploy react app to github pages'
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Use Node.js v${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run : npm i --force
        shell: bash
      - run : npm ci --force
        shell: bash
      - run: |
          touch .env
          echo VITE_API_KEY=${{ secrets.VITE_API_KEY }} >> .env
          echo VITE_BACKEND_URL=http://176.126.78.61:8080/api/ecoservice >> .env
          echo VITE_BACKEND_AUTH_URL=http://176.126.78.61:8080/api/auth >> .env
          echo VITE_GEOCODING_URL=https://maps.googleapis.com/maps/api/geocode/json >> .env
          cat .env
      - run : npm run build
        shell: bash
